# .cnb.yml
$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    - docker:
        # 自定义开发环境
        build:
          # 指定构建镜像的 Dockerfile 文件
          dockerfile: .ide/Dockerfile
          # 用来声明缓存构建过程中依赖的文件列表。
      services:
        # 声明使用 vscode 服务
        - vscode
        # 声明在容器中支持 docker 命令
        - docker
      stages:
        # 环境启动后需要执行的命令
        - name: 安装依赖
          script: 
            - echo "Done"
  tag_push:
    # 上传二进制包到 release 附件
    - docker:
        build: .ide/Dockerfile
      stages:
        - name: 更新日志
          image: cnbcool/changelog
          settings:
            day: 30
          exports:
            latestChangeLog: LATEST_CHANGE_LOG
        - name: 创建 release
          type: git:release
          options:
            latest: true
            description: ${LATEST_CHANGE_LOG}
        - name: 依赖安装和部署
          script: bash scripts/build.sh all
        - name: release 上传附件
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - rime-dict-processor-*
          exports:
            FILES: FILES
        - name: 输出附件
          script: echo $FILES